import React, { useState, useEffect } from "react";
import InfoSection from "./InfoSection";
import NavBar from "./NavBar";

export default function HomePage(){

    const [recievedData, setRecievedData] = useState({
        "location": {
            "name": "Las Vegas",
            "region": "Nevada",
            "country": "USA",
            "lat": 36.18,
            "lon": -115.12,
            "tz_id": "America/Los_Angeles",
            "localtime_epoch": 1659374974,
            "localtime": "2022-08-01 10:29"
        },
        "current": {
            "last_updated_epoch": 1659374100,
            "last_updated": "2022-08-01 10:15",
            "temp_c": 33.5,
            "temp_f": 92.3,
            "is_day": 1,
            "condition": {
                "text": "Sunny",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                "code": 1000
            },
            "wind_mph": 2.2,
            "wind_kph": 3.6,
            "wind_degree": 10,
            "wind_dir": "N",
            "pressure_mb": 1018,
            "pressure_in": 30.05,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 46,
            "cloud": 0,
            "feelslike_c": 38,
            "feelslike_f": 100.4,
            "vis_km": 16,
            "vis_miles": 9,
            "uv": 7,
            "gust_mph": 3.6,
            "gust_kph": 5.8
        },
        "forecast": {
            "forecastday": [
                {
                    "date": "2022-08-01",
                    "date_epoch": 1659312000,
                    "day": {
                        "maxtemp_c": 36.2,
                        "maxtemp_f": 97.2,
                        "mintemp_c": 26.8,
                        "mintemp_f": 80.2,
                        "avgtemp_c": 31.6,
                        "avgtemp_f": 88.9,
                        "maxwind_mph": 10.3,
                        "maxwind_kph": 16.6,
                        "totalprecip_mm": 4.7,
                        "totalprecip_in": 0.19,
                        "avgvis_km": 9.8,
                        "avgvis_miles": 6,
                        "avghumidity": 43,
                        "daily_will_it_rain": 1,
                        "daily_chance_of_rain": 83,
                        "daily_will_it_snow": 0,
                        "daily_chance_of_snow": 0,
                        "condition": {
                            "text": "Patchy rain possible",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "uv": 7
                    },
                    "astro": {
                        "sunrise": "05:48 AM",
                        "sunset": "07:46 PM",
                        "moonrise": "09:26 AM",
                        "moonset": "10:14 PM",
                        "moon_phase": "Waxing Crescent",
                        "moon_illumination": "22"
                    },
                    "hour": [
                        {
                            "time_epoch": 1659337200,
                            "time": "2022-08-01 00:00",
                            "temp_c": 28.4,
                            "temp_f": 83.1,
                            "is_day": 0,
                            "condition": {
                                "text": "Patchy rain possible",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                                "code": 1063
                            },
                            "wind_mph": 3.6,
                            "wind_kph": 5.8,
                            "wind_degree": 282,
                            "wind_dir": "WNW",
                            "pressure_mb": 1014,
                            "pressure_in": 29.95,
                            "precip_mm": 1,
                            "precip_in": 0.04,
                            "humidity": 54,
                            "cloud": 85,
                            "feelslike_c": 29.6,
                            "feelslike_f": 85.3,
                            "windchill_c": 28.4,
                            "windchill_f": 83.1,
                            "heatindex_c": 29.6,
                            "heatindex_f": 85.3,
                            "dewpoint_c": 18.2,
                            "dewpoint_f": 64.8,
                            "will_it_rain": 1,
                            "chance_of_rain": 74,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 9,
                            "vis_miles": 5,
                            "gust_mph": 4.9,
                            "gust_kph": 7.9,
                            "uv": 1
                        },
                        {
                            "time_epoch": 1659340800,
                            "time": "2022-08-01 01:00",
                            "temp_c": 28.2,
                            "temp_f": 82.8,
                            "is_day": 0,
                            "condition": {
                                "text": "Patchy rain possible",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                                "code": 1063
                            },
                            "wind_mph": 4.3,
                            "wind_kph": 6.8,
                            "wind_degree": 244,
                            "wind_dir": "WSW",
                            "pressure_mb": 1014,
                            "pressure_in": 29.94,
                            "precip_mm": 0.5,
                            "precip_in": 0.02,
                            "humidity": 55,
                            "cloud": 85,
                            "feelslike_c": 29.4,
                            "feelslike_f": 84.9,
                            "windchill_c": 28.2,
                            "windchill_f": 82.8,
                            "heatindex_c": 29.4,
                            "heatindex_f": 84.9,
                            "dewpoint_c": 18.2,
                            "dewpoint_f": 64.8,
                            "will_it_rain": 1,
                            "chance_of_rain": 83,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 9,
                            "vis_miles": 5,
                            "gust_mph": 5.8,
                            "gust_kph": 9.4,
                            "uv": 1
                        },
                        {
                            "time_epoch": 1659344400,
                            "time": "2022-08-01 02:00",
                            "temp_c": 26.8,
                            "temp_f": 80.2,
                            "is_day": 0,
                            "condition": {
                                "text": "Moderate or heavy rain shower",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/356.png",
                                "code": 1243
                            },
                            "wind_mph": 2.7,
                            "wind_kph": 4.3,
                            "wind_degree": 193,
                            "wind_dir": "SSW",
                            "pressure_mb": 1015,
                            "pressure_in": 29.98,
                            "precip_mm": 2.6,
                            "precip_in": 0.1,
                            "humidity": 59,
                            "cloud": 70,
                            "feelslike_c": 28,
                            "feelslike_f": 82.4,
                            "windchill_c": 26.8,
                            "windchill_f": 80.2,
                            "heatindex_c": 28,
                            "heatindex_f": 82.4,
                            "dewpoint_c": 18.2,
                            "dewpoint_f": 64.8,
                            "will_it_rain": 0,
                            "chance_of_rain": 69,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 7,
                            "vis_miles": 4,
                            "gust_mph": 4.3,
                            "gust_kph": 6.8,
                            "uv": 1
                        },
                        {
                            "time_epoch": 1659348000,
                            "time": "2022-08-01 03:00",
                            "temp_c": 26.9,
                            "temp_f": 80.4,
                            "is_day": 0,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                                "code": 1003
                            },
                            "wind_mph": 2.2,
                            "wind_kph": 3.6,
                            "wind_degree": 239,
                            "wind_dir": "WSW",
                            "pressure_mb": 1015,
                            "pressure_in": 29.97,
                            "precip_mm": 0,
                            "precip_in": 0,
                            "humidity": 59,
                            "cloud": 28,
                            "feelslike_c": 28.1,
                            "feelslike_f": 82.6,
                            "windchill_c": 26.9,
                            "windchill_f": 80.4,
                            "heatindex_c": 28.1,
                            "heatindex_f": 82.6,
                            "dewpoint_c": 18.2,
                            "dewpoint_f": 64.8,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10,
                            "vis_miles": 6,
                            "gust_mph": 3.4,
                            "gust_kph": 5.4,
                            "uv": 1
                        },
                        {
                            "time_epoch": 1659351600,
                            "time": "2022-08-01 04:00",
                            "temp_c": 27.1,
                            "temp_f": 80.8,
                            "is_day": 0,
                            "condition": {
                                "text": "Patchy rain possible",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                                "code": 1063
                            },
                            "wind_mph": 1.8,
                            "wind_kph": 2.9,
                            "wind_degree": 335,
                            "wind_dir": "NNW",
                            "pressure_mb": 1015,
                            "pressure_in": 29.96,
                            "precip_mm": 0.6,
                            "precip_in": 0.02,
                            "humidity": 58,
                            "cloud": 72,
                            "feelslike_c": 28.3,
                            "feelslike_f": 82.9,
                            "windchill_c": 27.1,
                            "windchill_f": 80.8,
                            "heatindex_c": 28.3,
                            "heatindex_f": 82.9,
                            "dewpoint_c": 18.1,
                            "dewpoint_f": 64.6,
                            "will_it_rain": 1,
                            "chance_of_rain": 82,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 9,
                            "vis_miles": 5,
                            "gust_mph": 2.9,
                            "gust_kph": 4.7,
                            "uv": 1
                        },
                        {
                            "time_epoch": 1659355200,
                            "time": "2022-08-01 05:00",
                            "temp_c": 27.1,
                            "temp_f": 80.8,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 0.7,
                            "wind_kph": 1.1,
                            "wind_degree": 6,
                            "wind_dir": "N",
                            "pressure_mb": 1014,
                            "pressure_in": 29.96,
                            "precip_mm": 0,
                            "precip_in": 0,
                            "humidity": 58,
                            "cloud": 15,
                            "feelslike_c": 28.4,
                            "feelslike_f": 83.1,
                            "windchill_c": 27.1,
                            "windchill_f": 80.8,
                            "heatindex_c": 28.4,
                            "heatindex_f": 83.1,
                            "dewpoint_c": 18.2,
                            "dewpoint_f": 64.8,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10,
                            "vis_miles": 6,
                            "gust_mph": 0.9,
                            "gust_kph": 1.4,
                            "uv": 1
                        },
                        {
                            "time_epoch": 1659358800,
                            "time": "2022-08-01 06:00",
                            "temp_c": 27,
                            "temp_f": 80.6,
                            "is_day": 1,
                            "condition": {
                                "text": "Sunny",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 1.3,
                            "wind_kph": 2.2,
                            "wind_degree": 132,
                            "wind_dir": "SE",
                            "pressure_mb": 1015,
                            "pressure_in": 29.97,
                            "precip_mm": 0,
                            "precip_in": 0,
                            "humidity": 59,
                            "cloud": 16,
                            "feelslike_c": 28.3,
                            "feelslike_f": 82.9,
                            "windchill_c": 27,
                            "windchill_f": 80.6,
                            "heatindex_c": 28.3,
                            "heatindex_f": 82.9,
                            "dewpoint_c": 18.4,
                            "dewpoint_f": 65.1,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10,
                            "vis_miles": 6,
                            "gust_mph": 1.6,
                            "gust_kph": 2.5,
                            "uv": 7
                        },
                        {
                            "time_epoch": 1659362400,
                            "time": "2022-08-01 07:00",
                            "temp_c": 27.3,
                            "temp_f": 81.1,
                            "is_day": 1,
                            "condition": {
                                "text": "Sunny",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 1.8,
                            "wind_kph": 2.9,
                            "wind_degree": 118,
                            "wind_dir": "ESE",
                            "pressure_mb": 1015,
                            "pressure_in": 29.98,
                            "precip_mm": 0,
                            "precip_in": 0,
                            "humidity": 56,
                            "cloud": 15,
                            "feelslike_c": 28.4,
                            "feelslike_f": 83.1,
                            "windchill_c": 27.3,
                            "windchill_f": 81.1,
                            "heatindex_c": 28.4,
                            "heatindex_f": 83.1,
                            "dewpoint_c": 17.9,
                            "dewpoint_f": 64.2,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10,
                            "vis_miles": 6,
                            "gust_mph": 2,
                            "gust_kph": 3.2,
                            "uv": 7
                        },
                        {
                            "time_epoch": 1659366000,
                            "time": "2022-08-01 08:00",
                            "temp_c": 28,
                            "temp_f": 82.4,
                            "is_day": 1,
                            "condition": {
                                "text": "Sunny",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 2.5,
                            "wind_kph": 4,
                            "wind_degree": 107,
                            "wind_dir": "ESE",
                            "pressure_mb": 1016,
                            "pressure_in": 29.99,
                            "precip_mm": 0,
                            "precip_in": 0,
                            "humidity": 54,
                            "cloud": 15,
                            "feelslike_c": 29.1,
                            "feelslike_f": 84.4,
                            "windchill_c": 28,
                            "windchill_f": 82.4,
                            "heatindex_c": 29.1,
                            "heatindex_f": 84.4,
                            "dewpoint_c": 17.8,
                            "dewpoint_f": 64,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10,
                            "vis_miles": 6,
                            "gust_mph": 2.9,
                            "gust_kph": 4.7,
                            "uv": 7
                        },
                        {
                            "time_epoch": 1659369600,
                            "time": "2022-08-01 09:00",
                            "temp_c": 29,
                            "temp_f": 84.2,
                            "is_day": 1,
                            "condition": {
                                "text": "Sunny",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 3.1,
                            "wind_kph": 5,
                            "wind_degree": 119,
                            "wind_dir": "ESE",
                            "pressure_mb": 1015,
                            "pressure_in": 29.98,
                            "precip_mm": 0,
                            "precip_in": 0,
                            "humidity": 50,
                            "cloud": 15,
                            "feelslike_c": 30.1,
                            "feelslike_f": 86.2,
                            "windchill_c": 29,
                            "windchill_f": 84.2,
                            "heatindex_c": 30.1,
                            "heatindex_f": 86.2,
                            "dewpoint_c": 17.7,
                            "dewpoint_f": 63.9,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10,
                            "vis_miles": 6,
                            "gust_mph": 3.6,
                            "gust_kph": 5.8,
                            "uv": 7
                        },
                        {
                            "time_epoch": 1659373200,
                            "time": "2022-08-01 10:00",
                            "temp_c": 30.1,
                            "temp_f": 86.2,
                            "is_day": 1,
                            "condition": {
                                "text": "Sunny",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 3.4,
                            "wind_kph": 5.4,
                            "wind_degree": 131,
                            "wind_dir": "SE",
                            "pressure_mb": 1015,
                            "pressure_in": 29.97,
                            "precip_mm": 0,
                            "precip_in": 0,
                            "humidity": 46,
                            "cloud": 15,
                            "feelslike_c": 31.1,
                            "feelslike_f": 88,
                            "windchill_c": 30.1,
                            "windchill_f": 86.2,
                            "heatindex_c": 31.1,
                            "heatindex_f": 88,
                            "dewpoint_c": 17.3,
                            "dewpoint_f": 63.1,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10,
                            "vis_miles": 6,
                            "gust_mph": 3.8,
                            "gust_kph": 6.1,
                            "uv": 8
                        },
                        {
                            "time_epoch": 1659376800,
                            "time": "2022-08-01 11:00",
                            "temp_c": 34.1,
                            "temp_f": 93.4,
                            "is_day": 1,
                            "condition": {
                                "text": "Sunny",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 3.8,
                            "wind_kph": 6.1,
                            "wind_degree": 140,
                            "wind_dir": "SE",
                            "pressure_mb": 1015,
                            "pressure_in": 29.97,
                            "precip_mm": 0,
                            "precip_in": 0,
                            "humidity": 42,
                            "cloud": 14,
                            "feelslike_c": 36.9,
                            "feelslike_f": 98.4,
                            "windchill_c": 34.1,
                            "windchill_f": 93.4,
                            "heatindex_c": 36.9,
                            "heatindex_f": 98.4,
                            "dewpoint_c": 19.4,
                            "dewpoint_f": 66.9,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10,
                            "vis_miles": 6,
                            "gust_mph": 4.5,
                            "gust_kph": 7.2,
                            "uv": 8
                        },
                        {
                            "time_epoch": 1659380400,
                            "time": "2022-08-01 12:00",
                            "temp_c": 35.4,
                            "temp_f": 95.7,
                            "is_day": 1,
                            "condition": {
                                "text": "Sunny",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 4.5,
                            "wind_kph": 7.2,
                            "wind_degree": 150,
                            "wind_dir": "SSE",
                            "pressure_mb": 1014,
                            "pressure_in": 29.95,
                            "precip_mm": 0,
                            "precip_in": 0,
                            "humidity": 38,
                            "cloud": 15,
                            "feelslike_c": 38.2,
                            "feelslike_f": 100.8,
                            "windchill_c": 35.4,
                            "windchill_f": 95.7,
                            "heatindex_c": 38.2,
                            "heatindex_f": 100.8,
                            "dewpoint_c": 19.1,
                            "dewpoint_f": 66.4,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10,
                            "vis_miles": 6,
                            "gust_mph": 5.1,
                            "gust_kph": 8.3,
                            "uv": 9
                        },
                        {
                            "time_epoch": 1659384000,
                            "time": "2022-08-01 13:00",
                            "temp_c": 34.2,
                            "temp_f": 93.6,
                            "is_day": 1,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                                "code": 1003
                            },
                            "wind_mph": 4.9,
                            "wind_kph": 7.9,
                            "wind_degree": 165,
                            "wind_dir": "SSE",
                            "pressure_mb": 1013,
                            "pressure_in": 29.92,
                            "precip_mm": 0,
                            "precip_in": 0,
                            "humidity": 35,
                            "cloud": 47,
                            "feelslike_c": 35.2,
                            "feelslike_f": 95.4,
                            "windchill_c": 34.2,
                            "windchill_f": 93.6,
                            "heatindex_c": 35.2,
                            "heatindex_f": 95.4,
                            "dewpoint_c": 16.5,
                            "dewpoint_f": 61.7,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10,
                            "vis_miles": 6,
                            "gust_mph": 5.6,
                            "gust_kph": 9,
                            "uv": 8
                        },
                        {
                            "time_epoch": 1659387600,
                            "time": "2022-08-01 14:00",
                            "temp_c": 35.3,
                            "temp_f": 95.5,
                            "is_day": 1,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                                "code": 1003
                            },
                            "wind_mph": 5.6,
                            "wind_kph": 9,
                            "wind_degree": 182,
                            "wind_dir": "S",
                            "pressure_mb": 1012,
                            "pressure_in": 29.89,
                            "precip_mm": 0,
                            "precip_in": 0,
                            "humidity": 31,
                            "cloud": 40,
                            "feelslike_c": 36.1,
                            "feelslike_f": 97,
                            "windchill_c": 35.3,
                            "windchill_f": 95.5,
                            "heatindex_c": 36.1,
                            "heatindex_f": 97,
                            "dewpoint_c": 15.8,
                            "dewpoint_f": 60.4,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10,
                            "vis_miles": 6,
                            "gust_mph": 6.5,
                            "gust_kph": 10.4,
                            "uv": 9
                        },
                        {
                            "time_epoch": 1659391200,
                            "time": "2022-08-01 15:00",
                            "temp_c": 36,
                            "temp_f": 96.8,
                            "is_day": 1,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                                "code": 1003
                            },
                            "wind_mph": 6.5,
                            "wind_kph": 10.4,
                            "wind_degree": 196,
                            "wind_dir": "SSW",
                            "pressure_mb": 1011,
                            "pressure_in": 29.86,
                            "precip_mm": 0,
                            "precip_in": 0,
                            "humidity": 29,
                            "cloud": 25,
                            "feelslike_c": 36.5,
                            "feelslike_f": 97.7,
                            "windchill_c": 36,
                            "windchill_f": 96.8,
                            "heatindex_c": 36.5,
                            "heatindex_f": 97.7,
                            "dewpoint_c": 14.9,
                            "dewpoint_f": 58.8,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10,
                            "vis_miles": 6,
                            "gust_mph": 7.4,
                            "gust_kph": 11.9,
                            "uv": 9
                        },
                        {
                            "time_epoch": 1659394800,
                            "time": "2022-08-01 16:00",
                            "temp_c": 36.2,
                            "temp_f": 97.2,
                            "is_day": 1,
                            "condition": {
                                "text": "Sunny",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 7.2,
                            "wind_kph": 11.5,
                            "wind_degree": 199,
                            "wind_dir": "SSW",
                            "pressure_mb": 1010,
                            "pressure_in": 29.83,
                            "precip_mm": 0,
                            "precip_in": 0,
                            "humidity": 27,
                            "cloud": 21,
                            "feelslike_c": 36.3,
                            "feelslike_f": 97.3,
                            "windchill_c": 36.2,
                            "windchill_f": 97.2,
                            "heatindex_c": 36.3,
                            "heatindex_f": 97.3,
                            "dewpoint_c": 14.1,
                            "dewpoint_f": 57.4,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10,
                            "vis_miles": 6,
                            "gust_mph": 8.3,
                            "gust_kph": 13.3,
                            "uv": 9
                        },
                        {
                            "time_epoch": 1659398400,
                            "time": "2022-08-01 17:00",
                            "temp_c": 36.2,
                            "temp_f": 97.2,
                            "is_day": 1,
                            "condition": {
                                "text": "Sunny",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 7.8,
                            "wind_kph": 12.6,
                            "wind_degree": 206,
                            "wind_dir": "SSW",
                            "pressure_mb": 1010,
                            "pressure_in": 29.81,
                            "precip_mm": 0,
                            "precip_in": 0,
                            "humidity": 27,
                            "cloud": 22,
                            "feelslike_c": 36.3,
                            "feelslike_f": 97.3,
                            "windchill_c": 36.2,
                            "windchill_f": 97.2,
                            "heatindex_c": 36.3,
                            "heatindex_f": 97.3,
                            "dewpoint_c": 14.2,
                            "dewpoint_f": 57.6,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10,
                            "vis_miles": 6,
                            "gust_mph": 8.9,
                            "gust_kph": 14.4,
                            "uv": 9
                        },
                        {
                            "time_epoch": 1659402000,
                            "time": "2022-08-01 18:00",
                            "temp_c": 35.7,
                            "temp_f": 96.3,
                            "is_day": 1,
                            "condition": {
                                "text": "Sunny",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 9.6,
                            "wind_kph": 15.5,
                            "wind_degree": 223,
                            "wind_dir": "SW",
                            "pressure_mb": 1009,
                            "pressure_in": 29.8,
                            "precip_mm": 0,
                            "precip_in": 0,
                            "humidity": 28,
                            "cloud": 19,
                            "feelslike_c": 36,
                            "feelslike_f": 96.8,
                            "windchill_c": 35.7,
                            "windchill_f": 96.3,
                            "heatindex_c": 36,
                            "heatindex_f": 96.8,
                            "dewpoint_c": 14.6,
                            "dewpoint_f": 58.3,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10,
                            "vis_miles": 6,
                            "gust_mph": 11.2,
                            "gust_kph": 18,
                            "uv": 9
                        },
                        {
                            "time_epoch": 1659405600,
                            "time": "2022-08-01 19:00",
                            "temp_c": 35.4,
                            "temp_f": 95.7,
                            "is_day": 1,
                            "condition": {
                                "text": "Sunny",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 10.3,
                            "wind_kph": 16.6,
                            "wind_degree": 228,
                            "wind_dir": "SW",
                            "pressure_mb": 1009,
                            "pressure_in": 29.81,
                            "precip_mm": 0,
                            "precip_in": 0,
                            "humidity": 30,
                            "cloud": 15,
                            "feelslike_c": 35.9,
                            "feelslike_f": 96.6,
                            "windchill_c": 35.4,
                            "windchill_f": 95.7,
                            "heatindex_c": 35.9,
                            "heatindex_f": 96.6,
                            "dewpoint_c": 15.2,
                            "dewpoint_f": 59.4,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10,
                            "vis_miles": 6,
                            "gust_mph": 11.9,
                            "gust_kph": 19.1,
                            "uv": 9
                        },
                        {
                            "time_epoch": 1659409200,
                            "time": "2022-08-01 20:00",
                            "temp_c": 34.2,
                            "temp_f": 93.6,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 9.8,
                            "wind_kph": 15.8,
                            "wind_degree": 234,
                            "wind_dir": "SW",
                            "pressure_mb": 1010,
                            "pressure_in": 29.82,
                            "precip_mm": 0,
                            "precip_in": 0,
                            "humidity": 33,
                            "cloud": 17,
                            "feelslike_c": 34.7,
                            "feelslike_f": 94.5,
                            "windchill_c": 34.2,
                            "windchill_f": 93.6,
                            "heatindex_c": 34.7,
                            "heatindex_f": 94.5,
                            "dewpoint_c": 15.4,
                            "dewpoint_f": 59.7,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10,
                            "vis_miles": 6,
                            "gust_mph": 11.4,
                            "gust_kph": 18.4,
                            "uv": 1
                        },
                        {
                            "time_epoch": 1659412800,
                            "time": "2022-08-01 21:00",
                            "temp_c": 33.7,
                            "temp_f": 92.7,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 8.5,
                            "wind_kph": 13.7,
                            "wind_degree": 238,
                            "wind_dir": "WSW",
                            "pressure_mb": 1010,
                            "pressure_in": 29.84,
                            "precip_mm": 0,
                            "precip_in": 0,
                            "humidity": 34,
                            "cloud": 12,
                            "feelslike_c": 34.4,
                            "feelslike_f": 93.9,
                            "windchill_c": 33.7,
                            "windchill_f": 92.7,
                            "heatindex_c": 34.4,
                            "heatindex_f": 93.9,
                            "dewpoint_c": 15.8,
                            "dewpoint_f": 60.4,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10,
                            "vis_miles": 6,
                            "gust_mph": 9.8,
                            "gust_kph": 15.8,
                            "uv": 1
                        },
                        {
                            "time_epoch": 1659416400,
                            "time": "2022-08-01 22:00",
                            "temp_c": 33.1,
                            "temp_f": 91.6,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 6.7,
                            "wind_kph": 10.8,
                            "wind_degree": 237,
                            "wind_dir": "WSW",
                            "pressure_mb": 1011,
                            "pressure_in": 29.84,
                            "precip_mm": 0,
                            "precip_in": 0,
                            "humidity": 36,
                            "cloud": 11,
                            "feelslike_c": 33.8,
                            "feelslike_f": 92.8,
                            "windchill_c": 33.1,
                            "windchill_f": 91.6,
                            "heatindex_c": 33.8,
                            "heatindex_f": 92.8,
                            "dewpoint_c": 16.1,
                            "dewpoint_f": 61,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10,
                            "vis_miles": 6,
                            "gust_mph": 8.3,
                            "gust_kph": 13.3,
                            "uv": 1
                        },
                        {
                            "time_epoch": 1659420000,
                            "time": "2022-08-01 23:00",
                            "temp_c": 32.7,
                            "temp_f": 90.9,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 6.5,
                            "wind_kph": 10.4,
                            "wind_degree": 223,
                            "wind_dir": "SW",
                            "pressure_mb": 1011,
                            "pressure_in": 29.85,
                            "precip_mm": 0,
                            "precip_in": 0,
                            "humidity": 37,
                            "cloud": 16,
                            "feelslike_c": 33.4,
                            "feelslike_f": 92.1,
                            "windchill_c": 32.7,
                            "windchill_f": 90.9,
                            "heatindex_c": 33.4,
                            "heatindex_f": 92.1,
                            "dewpoint_c": 16.1,
                            "dewpoint_f": 61,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10,
                            "vis_miles": 6,
                            "gust_mph": 8.3,
                            "gust_kph": 13.3,
                            "uv": 1
                        }
                    ]
                }
            ]
        }
    })

    const [defaultZip, setDefaultZip] = useState("07305")
    

    let getData = (zip) => { 

        fetch(`http://api.weatherapi.com/v1/forecast.json?key=b28574dd6599479e944222901212812&q=${zip}`)
        .then((response) => response.json())
        .then((data) => {
            setRecievedData(data)
        })
        .catch(err => console.error(err))

    }
    
    useEffect(() => 
    {
     getData(defaultZip);
    }, [""]);

    return(
        <div className="home-page">
            <NavBar
                dataObject={recievedData}
            />
            <InfoSection />
        </div>
    )
}